baseurl: "https://dev.crokmou.com/"
languageCode: "fr-FR"
title: "Crokmou"
metaDataFormat: "yaml"
theme: "crokmou"

sectionPagesMenu: "main"
RemovePathAccents: true
permalinks:
  blog: /:year/:month/:slug/

params:
  socials:
    - id: "facebook"
      href: "/facebook/"
    - id: "gplus"
      href: "/gplus/"
    - id: "instagram"
      href: "/instagram/"
    - id: "pinterest"
      href: "/pinterest/"
    - id: "twitter"
      href: "/twitter/"
    - id: "youtube"
      href: "/youtube/"