baseurl: "https://www.crokmou.com/"
languageCode: "fr-FR"
title: "Crokmou"
metaDataFormat: "yaml"
theme: "crokmou"

sectionPagesMenu: "main"
RemovePathAccents: true
permalinks:
  blog: /:year/:month/:slug/
  recettes: /:year/:month/:slug/
  saveurs du monde: /:year/:month/:slug/
  restaurants: /:year/:month/:slug/
  carnet de voyage: /:year/:month/:slug/
  pages: /:slug/

disqusShortname: "crokmou"

menu:
  header:
      - Name: "Blog"
        Weight: 5
        Identifier: "blog"
        URL: "/blog/"
      - Name: "Carnet de voyage"
        Weight: 1
        Identifier: "carnet-de-voyage"
        URL: "/carnet-de-voyage/"
      - Name: "Recettes"
        Weight: 3
        Identifier: "recettes"
        URL: "/recettes/"
      - Name: "Restaurants"
        Weight: 4
        Identifier: "restaurants"
        URL: "/restaurants/"
      - Name: "Saveurs du monde"
        Weight: 2
        Identifier: "saveurs-du-monde"
        URL: "/saveurs-du-monde/"
      - Name: "A propos"
        Weight: 6
        Identifier: "a-propos"
        URL: "/a-propos/"
  footer:
      - Name: "Blog"
        Weight: 5
        Identifier: "blog"
        URL: "/blog/"
      - Name: "Carnet de voyage"
        Weight: 1
        Identifier: "carnet-de-voyage"
        URL: "/carnet-de-voyage/"
      - Name: "Recettes"
        Weight: 3
        Identifier: "recettes"
        URL: "/recettes/"
      - Name: "Restaurants"
        Weight: 4
        Identifier: "restaurants"
        URL: "/restaurants/"
      - Name: "Saveurs du monde"
        Weight: 2
        Identifier: "saveurs-du-monde"
        URL: "/saveurs-du-monde/"
  sections:
      - Name: "Manger à Bruxelles"
        Identifier: "manger-a-bruxelles"
        URL: "/manger-a-bruxelles/"
        Pre: "https://cdn.rawgit.com/crokmou/images/1.0.6/i/pate-pesto-pistache-amande-huile-concass%C3%A9-tomate-crokmou-blog-belge-cuisine-voyage-01.jpg"
      - Name: "Photo"
        Identifier: "photo"
        URL: "/photo/"
        Pre: "https://cdn.rawgit.com/crokmou/images/1.0.6/i/pate-pesto-pistache-amande-huile-concass%C3%A9-tomate-crokmou-blog-belge-cuisine-voyage-01.jpg"
  divers:
      - Name: "A propos"
        Weight: 2
        Identifier: "a-propos"
        URL: "/a-propos/"
      - Name: "Partenariats"
        Weight: 2
        Identifier: "partenariats"
        URL: "/partenariats/"

taxonomies:
  tag: ""

params:
  socials:
    - id: "facebook"
      href: "https://www.facebook.com/crokmou.blog/"
    - id: "instagram"
      href: "https://www.instagram.com/crokmou.blog/"
    - id: "pinterest"
      href: "https://www.pinterest.com/blogcrokmou/"
    - id: "youtube"
      href: "https://www.youtube.com/channel/UCI2nEqc0lxItG3iNDBd9Umw"
  highlight:
    - "pancakes-vegan-moelleux"
    - "dormir-eglise-hotel-martins-patershof-a-malines-belgique"
    - "san-bol-experience-culinaire-vegan-bruxelles"
  sidebar:
    - id: "breve"
      title: "Brèves"
    - id: "theme"
      title: "Soirées d'hiver"
      articles:
        - "lentilles-corail-au-lait-de-coco-curry-recette-vegan"
        - "burgers-savoyards-vegetariens"
        - "falafels-vegan-rapides-delicieux"
        - "brownie-vegan-gourmand-chocolate"
        - "riz-au-lait-vegetal-a-lorange"
    - id: "tips"
      title: "Astuce d'une blogueuse"
      thumbnail: ""
      articles:
        - "les-appareils-photos-numeriques-ou-apn"
        - "choisir-son-reflex-photographie"
        - "passer-en-mode-manuel-photographie"
        - "dompter-la-lumiere-photographie"
