baseurl: "https://dev.crokmou.com/"
languageCode: "fr-FR"
title: "Crokmou"
metaDataFormat: "yaml"
theme: "crokmou"

sectionPagesMenu: "main"
RemovePathAccents: true
permalinks:
  blog: /:year/:month/:slug/
  recettes: /:year/:month/:slug/
  saveur du monde: /:year/:month/:slug/
  restaurants: /:year/:month/:slug/
  carnet de voyage: /:year/:month/:slug/

taxonomies:
  tag: ""

params:
  socials:
    - id: "facebook"
      href: "/facebook/"
    - id: "gplus"
      href: "/gplus/"
    - id: "instagram"
      href: "/instagram/"
    - id: "pinterest"
      href: "/pinterest/"
    - id: "twitter"
      href: "/twitter/"
    - id: "youtube"
      href: "/youtube/"
  sidebar:
    - id: "breve"
      title: "Brèves"
    - id: "theme"
      title: "Un peu de soleil"
      articles:
        - "feta-marinee"
        - "tarte-aux-peches-ylang-ylang-et-romarin"
    - id: "tips"
      title: "Astuce d'une blogueuse"
      articles:
        - "feta-marinee"
