baseurl: "https://crokmou.com/"
languageCode: "fr-FR"
title: "Blog cuisine & Voyage"
metaDataFormat: "yaml"
theme: "crokmou"

sectionPagesMenu: "main"
RemovePathAccents: true
permalinks:
  blog: /:year/:month/:slug/
  recettes: /:year/:month/:slug/
  saveurs du monde: /:year/:month/:slug/
  restaurants: /:year/:month/:slug/
  carnet de voyage: /:year/:month/:slug/
  pages: /:slug/

disqusShortname: "crokmou"

menu:
  header:
      - Name: "Blog"
        Weight: 5
        Identifier: "blog"
        URL: "/blog/"
      - Name: "Carnet de voyage"
        Weight: 1
        Identifier: "carnet-de-voyage"
        URL: "/carnet-de-voyage/"
      - Name: "Recettes"
        Weight: 3
        Identifier: "recettes"
        URL: "/recettes/"
      - Name: "Restaurants"
        Weight: 4
        Identifier: "restaurants"
        URL: "/restaurants/"
      - Name: "Saveurs du monde"
        Weight: 2
        Identifier: "saveurs-du-monde"
        URL: "/saveurs-du-monde/"
      - Name: "A propos"
        Weight: 6
        Identifier: "a-propos"
        URL: "/a-propos/"
  footer:
      - Name: "Blog"
        Weight: 5
        Identifier: "blog"
        URL: "/blog/"
      - Name: "Carnet de voyage"
        Weight: 1
        Identifier: "carnet-de-voyage"
        URL: "/carnet-de-voyage/"
      - Name: "Recettes"
        Weight: 3
        Identifier: "recettes"
        URL: "/recettes/"
      - Name: "Restaurants"
        Weight: 4
        Identifier: "restaurants"
        URL: "/restaurants/"
      - Name: "Saveurs du monde"
        Weight: 2
        Identifier: "saveurs-du-monde"
        URL: "/saveurs-du-monde/"
  sections:
      - Name: "Manger à Bruxelles"
        Identifier: "manger-a-bruxelles"
        URL: "/manger-a-bruxelles/"
        Pre: "/pate-pesto-pistache-amande-huile-concass%C3%A9-tomate-crokmou-blog-belge-cuisine-voyage-01.jpg"
      - Name: "Photo"
        Identifier: "photo"
        URL: "/photo/"
        Pre: "/pate-pesto-pistache-amande-huile-concass%C3%A9-tomate-crokmou-blog-belge-cuisine-voyage-01.jpg"
  divers:
      - Name: "A propos"
        Weight: 2
        Identifier: "a-propos"
        URL: "/a-propos/"
      - Name: "Partenariats"
        Weight: 2
        Identifier: "partenariats"
        URL: "/partenariats/"

taxonomies:
  tag: ""

params:
  socials:
    - id: "facebook"
      href: "https://www.facebook.com/crokmou.blog/"
    - id: "instagram"
      href: "https://www.instagram.com/crokmou.blog/"
    - id: "pinterest"
      href: "https://www.pinterest.com/blogcrokmou/"
    - id: "youtube"
      href: "https://www.youtube.com/channel/UCI2nEqc0lxItG3iNDBd9Umw"
  highlight:
    - "gnocchis-a-l-ail-des-ours"
    - "spaghetti-bolognaise-vegan-legumes"
    - "visiter-jardins-villa-borghese-rome"
  sidebar:
    - id: "breve"
      title: "Brèves"
    - id: "theme"
      title: "Retour du soleil"
      articles:
        - "makis-faits-maison-vg-recette-video"
        - "falafels-vegan-rapides-delicieux"
        - "pate-levee-feuilletee-un-classique"
        - "pancakes-pralines-vegan"
        - "pates-epeautre-artichauts-poivrade-tomates-cerises-et-burrata"
    - id: "tips"
      title: "Astuce d'une blogueuse"
      thumbnail: ""
      articles:
        - "les-appareils-photos-numeriques-ou-apn"
        - "choisir-son-reflex-photographie"
        - "passer-en-mode-manuel-photographie"
        - "dompter-la-lumiere-photographie"
